### ISSUE TITLE
App forces user to switch to Ethereum network

### ISSUE THREAD

**Issue by kleb-33** [SporosDAO/sweat-token#112]
When connecting metamask wallet to the sporos app, I am prompted to switch to the ethereum network. This is obviously not what I wish to do, but if I refuse I am unable to connect my wallet to sporos. Instead I have to let MM switch me to Ethereum and then switch back to Arbitrum manually afterwards.

![image](https://user-images.githubusercontent.com/91540657/184142594-e14bd122-3514-43fc-915a-9cc4636705d0.png)

**Comment by ivelin** [comment]
Workaround implemented. Default chain is Goerli in dev mode and Arbitrum in prod mode.
https://github.com/SporosDAO/sweat-token/blob/7280e48861514db7c7da7b59fbd70af8c50eac77/frontend/src/context/Web3Context/index.tsx#L26

We need to gather more user feedback to decide on the optimal choice for initial chain on wallet connect.
Since users can interact with DAOs on multiple chains, it is not immediately clear which should be the initial chain on wallet connect. When in the context of a particular DAO page, then we can default to the DAO's native chain. Feedback welcome.
